version: "3.9"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.python
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.react
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/app
  postgres:
    image: "postgres:14"
    environment:
      POSTGRES_PASSWORD: "toor"
      POSTGRES_USER: "root"
      POSTGRES_DB: "bookstore"
    ports:
      - "5432:5432"