# Generated by Django 3.2.8 on 2021-11-12 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.TextField()),
                ('author_bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.TextField()),
                ('book_summary', models.TextField()),
                ('book_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('book_cover_photo', models.CharField(max_length=20)),
                ('author_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookstore.authors')),
            ],
        ),
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=120)),
                ('category_desc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.BigIntegerField()),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_title', models.CharField(max_length=120)),
                ('review_details', models.TextField()),
                ('review_date', models.BigIntegerField()),
                ('rating_star', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=3)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.books')),
            ],
        ),
        migrations.CreateModel(
            name='order_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('book_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookstore.books')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.orders')),
            ],
        ),
        migrations.CreateModel(
            name='discounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discounts_start_date', models.BigIntegerField()),
                ('discounts_end_date', models.BigIntegerField()),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('book_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookstore.books')),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='category_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookstore.categories'),
        ),
    ]
