# Generated by Django 3.2.8 on 2021-11-16 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
