# Generated by Django 3.2.8 on 2021-11-17 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20211116_1229'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
