FROM node:16
ARG UNAME=randomuser
ARG UID=1000
ARG GID=1000
WORKDIR /app
COPY . .
WORKDIR /app/bookworm/bookstore
RUN npm install
RUN groupadd -g $GID -o $UNAME
RUN useradd -m -u $UID -g $GID -o -s /bin/bash $UNAME
USER $UNAME
ENTRYPOINT [ "npm", "start" ]
